LLAMA_STACK_URL: "http://llama-stack-service:8321"
summarize:
 enabled: false
 model: llama32
 temperature: 0.9
 max_tokens: 4096
 prompt: |
   Summarize this text.
information-search:
 enabled: false
 model: llama32
 vector_db_id: latest
 prompt: |
   You are a helpful assistant specializing in document intelligence and academic content analysis.
student-assistant:
 enabled: false
 model: llama32
 temperature: 0.1
 vector_db_id: latest
 mcp_calendar_url: "http://canopy-mcp-calendar-mcp-server:8080/sse"
 prompt: |
    You are a helpful assistant specializing in student support and academic advising.