---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-backend
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"llama-stack"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy-backend
  template:
    metadata:
      labels:
        app: canopy-backend
      annotations:
        configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        instrumentation.opentelemetry.io/inject-python: redhat-ods-monitoring/data-science-instrumentation
    spec:
      containers:
        - name: canopy-backend
          image: quay.io/rhoai-genaiops/canopy-be:0.9
          ports:
            - containerPort: 8000
          env:
            - name: LLAMA_BASE_URL
              value: "{{ .Values.LLAMA_STACK_URL }}"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          volumeMounts:
            - mountPath: /canopy
              name: canopy-config
      volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: canopy-config.yaml
              path: canopy-config.yaml
            name: canopy-config
          name: canopy-config